[[dependencies]]
  name = "github.com/Sirupsen/logrus"
  version = ">=0.11.5, <1.0.0"

[[dependencies]]
  name = "github.com/crosbymichael/octokat"
  revision = "dea6d22fe9758677f9f6d56c62a91269705a241f"
